### PR TITLE
Add CSS Flexbox

### PR DESCRIPTION
**Pull request by swardhan**
Added CSS Flexbox Tab.

### CODE REVIEW

**Comment by Sherawat42** [comment]
First of all good work buddy!!
There is an issue with the spacing wherever code is written in your branch vs branch he master branch. I have uploaded the screenshots. Please try to fix this, then your will surely be merged! If you have any doubt feel free to post here...

Your branch
image
The Master Branch
image

**Comment by swardhan** [comment]
Its the xmp tag. The output is coming as I have indented in the html source.

**Comment by Sherawat42** [comment]
Oh then try writing a script in ruby or python to parse the file and wherever you find '<xmp>' start re-indenting and stop whenever you get '</xmp>'. Try this, its going to be fun

**Comment by swardhan** [comment]
Not that good in either (Ruby or Python). It wasn't much so I did it by myself. You can check now.

**Comment by Sherawat42** [comment]
Maybe you need to push your changes...

**Pull request closed without merging**
